heat_template_version: ocata

parameters:
  key_name:
    type: string
  flavor:
    type: string
  image:
    type: string
  private_net:
    type: string
  public_net:
    type: string
    default: ''

conditions:
  has_public_network:
    not:
      equals:
      - {get_param: public_net}
      - ''

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for hadoop cluster
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 50070
          port_range_max: 50070
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 9000
          port_range_max: 9000
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 50075
          port_range_max: 50075

  server:
    type: OS::Nova::Server
    properties:
      image:
        get_param: image
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      networks:
      - port: {get_resource: server_port}
      user_data_format: SOFTWARE_CONFIG

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      security_groups: 
      - { get_resource: security_group } 

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    condition: has_public_network
    properties:
      floating_network_id: { get_param: public_net }
      port_id: { get_resource: server_port }

outputs:
  slave_ip:
    value:
      get_attr: [server, first_address]
  slave_id:
    value:
      get_resource: server
