heat_template_version: ocata

parameters:
  key_name:
    type: string
  flavor:
    type: string
  image:
    type: string
  private_net:
    type: string
  security_group:
    type: string

resources:
  server_a:
    type: OS::Nova::Server
    properties:
      image:
        get_param: image
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      networks:
      - network: {get_param: private_net}
      security_groups: [{ get_param: security_group }]
      user_data_format: SOFTWARE_CONFIG

outputs:
  slave_ip:
    value:
      get_attr: [server_a, first_address]
  slave_id:
    value:
      get_resource: server_a
