heat_template_version: ocata
#
# The demo is about similar function with ssh-copy-id.
#
# Say we have two virtual machine, server A and server B. Server B
# wants to add its id_rsa.pub contents into authorized_keys of server
# A. So that server B can talk with server A via ssh without password.
#

parameters:
  key_name:
    type: string
#    default: undercloud
  flavor:
    type: string
#    default: disk-small
  image:
    type: string
#    default: heat-image
  private_net:
    type: string
#    default: private

resources:
  server_a:
    type: OS::Nova::Server
    properties:
      image:
        get_param: image
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      networks:
      - network: {get_param: private_net}
      block_device_mapping: [{"volume_id": { get_resource: volume_storage },
                              "delete_on_termination": true,
                              "device_name": "vda"}]
      user_data_format: SOFTWARE_CONFIG

  volume_storage:
   type: OS::Cinder::Volume
   properties:
    size: 40
    image: {get_param: image}
    volume_type: nfs2

outputs:
  slave_ip:
    value:
      get_attr: [server_a, first_address]
  slave_id:
    value:
      get_resource: server_a
